---
title: "World GDP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(geojsonio)
library(viridis)
```

### 8 Aug 2020 (data from before 2020)
[Link to GeoJSON data](https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson)

```{r test2, echo=FALSE}
countries <- geojsonio::geojson_read("countries.geojson", what="sp")
b <- c(-100, 1e5, 5e5, 1e6, 2e6, 3e6, 5e6, 2e7)
pal <- colorBin("plasma", domain = countries$gdp_md_est, bins = b)
lbls <- sprintf("%s GDP: $%.2f", countries$admin, countries$gdp_md_est)

m <- leaflet(countries) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN'))) %>% addPolygons(
  fillColor = ~pal(gdp_md_est),
  weight = 1,
  opacity = 1,
  color = "#aaa",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 3,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = lbls) %>% 
addLegend(pal = pal, values = ~gdp_md_est, opacity = 0.7, title = NULL,
  position = "bottomright")
m
```